// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9X5eNZBVT0DkFT_aA802f6vQKFsCd6w',
    appId: '1:114264872440:web:d499f2032bf8b85c74f20d',
    messagingSenderId: '114264872440',
    projectId: 'flutter-data-firebase-f22c7',
    authDomain: 'flutter-data-firebase-f22c7.firebaseapp.com',
    storageBucket: 'flutter-data-firebase-f22c7.appspot.com',
    measurementId: 'G-8BD8J8EZ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyz5XaJUGUXnzVlDgz6_YpFbBUQBUBO4o',
    appId: '1:114264872440:android:d60358261b8a63ad74f20d',
    messagingSenderId: '114264872440',
    projectId: 'flutter-data-firebase-f22c7',
    storageBucket: 'flutter-data-firebase-f22c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZyohpYDjLfrBwGyT6EWc-U2PFI8_osA',
    appId: '1:114264872440:ios:2b4d0b7f20a1b5b374f20d',
    messagingSenderId: '114264872440',
    projectId: 'flutter-data-firebase-f22c7',
    storageBucket: 'flutter-data-firebase-f22c7.appspot.com',
    iosClientId: '114264872440-ie19hb99oqd13in7h7mrgnp3v53efooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloFlutterWirhIntellij',
  );
}
